### ISSUE TITLE
Actividad 6 Proceso de negocio mejorado

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-con-web-30-mejorado-equipo-v-a-k#1]
[Practica6-Proceso-mejorado-de-negocio.pdf](https://github.com/user-attachments/files/17182359/Practica6-Proceso-mejorado-de-negocio.pdf)

**Comment by ErikCuevas03** [comment]
El contenido esta acorde a la rubrica, pero si falto explicar más a detalle 
Calificación : 19/20

**Comment by josealfredo79** [comment]
NO es un proceso de Negocio no se puede evaluar.. @ErikCuevas03 favor de checar por favor

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
